---
- hosts: debian
  tasks:
    - name: Installer Apache
      ansible.builtin.apt:
        name=apache2 state=present update_cache=true

    - name: Installer Php7
      ansible.builtin.apt:
        name=libapache2-mod-php7.4 state=present

    - name: Démarrer le service Apache
      ansible.builtin.service:
        name=apache2 state=started enabled=true

    - name: copier un phpinfo
      ansible.builtin.copy:
        src=info.php dest=/var/www/html/index.php owner=www-data group=www-data mode=0664
